//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseShowAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int CatalogId { get; set; }
        public Nullable<int> HorseRegistrationId { get; set; }
        public Nullable<int> ShowId { get; set; }
        public Nullable<int> RegistrationReferenceNo { get; set; }
        public string HorseNameEn { get; set; }
        public string HorseNameAr { get; set; }
        public string SireEn { get; set; }
        public string SireAr { get; set; }
        public string DamEn { get; set; }
        public string DamAr { get; set; }
        public string Sex { get; set; }
        public string SexAr { get; set; }
        public string Color { get; set; }
        public string ColorAr { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string HorseBreederName { get; set; }
        public string HorseBreederNameAr { get; set; }
        public string HorseBreederAddress { get; set; }
        public string HorseBreederAdreessAr { get; set; }
        public string HbCountryEn { get; set; }
        public string HbCountryAr { get; set; }
        public string HorsePassportCopy { get; set; }
        public string OwnerName { get; set; }
        public string OwnerNameAr { get; set; }
        public string AddressEn { get; set; }
        public string AddressAr { get; set; }
        public string POBox { get; set; }
        public string POBoxAr { get; set; }
        public string City { get; set; }
        public string CityAr { get; set; }
        public string Country { get; set; }
        public string CountryAr { get; set; }
        public string Telephone { get; set; }
        public string TelephoneAr { get; set; }
        public string Fax { get; set; }
        public string FaxAr { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string MobileAr { get; set; }
        public string ECAHOClasses { get; set; }
        public string ECAHOClassesAr { get; set; }
        public string NonECAHOClasses { get; set; }
        public string NonECAHOClassesAr { get; set; }
        public string OwnerPassportCopy { get; set; }
        public Nullable<System.DateTime> DateEn { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string ShowNameHrEn { get; set; }
        public string ShowNameHrAr { get; set; }
        public Nullable<System.DateTime> DateHr { get; set; }
        public string ClassHrEn { get; set; }
        public string ClassHrAr { get; set; }
        public string PlaceHrEn { get; set; }
        public string PlaceHrAr { get; set; }
        public string CountryHrEn { get; set; }
        public string CountryHrAr { get; set; }
        public string PositionHrEn { get; set; }
        public string PositionHrAr { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CatalogNumber { get; set; }
        public Nullable<bool> IsCatalogDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public string RatedJudgesIDList { get; set; }
        public Nullable<bool> RatingDone { get; set; }
        public string MobileCountry { get; set; }
        public Nullable<bool> IsExceptionCase { get; set; }
        public string OwnerPassportImageName { get; set; }
        public string HorsePassportImageName { get; set; }
        public string RegisterUserName { get; set; }
        public string ClassName { get; set; }
        public bool IsSplit { get; set; }
        public Nullable<decimal> HorseScore { get; set; }
        public Nullable<decimal> Type { get; set; }
        public Nullable<decimal> Moves { get; set; }
        public string BaseClassName { get; set; }
        public Nullable<bool> ShowHorseActive { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<decimal> ChampionshipScore { get; set; }
        public Nullable<int> ChamionshipId { get; set; }
        public Nullable<int> WinnerTypeId { get; set; }
    }
}
