//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseShowAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionshipRating
    {
        public int ChampionshipRatingId { get; set; }
        public Nullable<int> WinnerTypeId { get; set; }
        public Nullable<int> ChampionShipJudgeId { get; set; }
        public Nullable<int> HorseCatalog { get; set; }
        public string IpadUdid { get; set; }
        public Nullable<int> Showid { get; set; }
        public Nullable<int> ChampionshipId { get; set; }
    }
}
