//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseShowAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowClassHors
    {
        public int ShowClassHorsesId { get; set; }
        public Nullable<int> ShowClassId { get; set; }
        public Nullable<int> ShowId { get; set; }
        public Nullable<int> ShowHorseId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> HorseScore { get; set; }
        public string RatedJudgesIDList { get; set; }
    }
}
