//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseShowAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowJudgeCode
    {
        public int ShowJudgeCodeId { get; set; }
        public Nullable<int> ShowId { get; set; }
        public string JudgeCode { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
