//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseShowAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowClassJudge
    {
        public int ShowClassJudgesId { get; set; }
        public Nullable<int> ShowId { get; set; }
        public Nullable<int> ShowClassId { get; set; }
        public Nullable<int> ShowJudgesId { get; set; }
        public bool IsActive { get; set; }
    }
}
